/**
 * Supabase env가 없을 때(로컬 미리보기) 사용하는 시드 데이터.
 * supabase/seed.sql 과 내용을 동일하게 유지한다.
 * 출처: TRL.md §8(멤버 확정값), legacy/script.js(경기 결과·소식 실데이터)
 */
import type { Car, GalleryImage, Member, NewsPost, Race, SiteSettings } from '@/types/content';

export const members: Member[] = [
  {
    id: 'm-01',
    slug: 'junhee-kim',
    racing_number: '01',
    name: 'Junhee Kim',
    field: 'Onroad',
    role: 'driver',
    favorite_car: 'McLaren 720S GT3',
    favorite_track: 'Sebring',
    birth_year: 2010,
    wheel_base: 'MOZA R12',
    pedal: 'MOZA CRP2',
    instagram: 'jxnh_72',
    bio_ko: null,
    bio_en: 'Currently playing LMU for certain reasons, returning soon.',
    profile_image_url: null,
    helmet_image_url: '/members/junhee_helmet.png',
    is_published: true,
    sort_order: 1,
  },
  {
    id: 'm-02',
    slug: 'chanwoo-kim',
    racing_number: '02',
    name: 'Chanwoo Kim',
    field: 'Onroad',
    role: 'driver',
    favorite_car: 'BMW M4 GT3',
    favorite_track: 'Spa-Francorchamps',
    birth_year: 2009,
    wheel_base: 'Logitech G27',
    pedal: 'Logitech G27',
    instagram: 'cw__0115',
    bio_ko: null,
    bio_en: 'Using G27 to save up, returning to iRacing soon.',
    profile_image_url: null,
    helmet_image_url: '/members/chanwoo_helmet.png',
    is_published: true,
    sort_order: 2,
  },
  {
    id: 'm-03',
    slug: 'jihoo-park',
    racing_number: '03',
    name: 'Jihoo Park',
    field: 'Onroad',
    role: 'driver',
    favorite_car: 'SF-24',
    favorite_track: 'Long Beach',
    birth_year: 2009,
    wheel_base: 'MOZA R25',
    pedal: 'MOZA SRP2',
    instagram: 'ji_hoo324',
    bio_ko: null,
    bio_en: 'Enduring the full torque of R25 with his entire body.',
    profile_image_url: null,
    helmet_image_url: '/members/jihoo_helmet.png',
    is_published: true,
    sort_order: 3,
  },
  {
    id: 'm-04',
    slug: 'minsoo-seo',
    racing_number: '04',
    name: 'Minsoo Seo',
    field: 'Onroad',
    role: 'driver',
    favorite_car: 'Toyota GR86',
    favorite_track: 'Interlagos',
    birth_year: 2010,
    wheel_base: 'MOZA R9 V2',
    pedal: 'MOZA CRP2',
    instagram: 'm1nso0.10',
    bio_ko: null,
    bio_en: 'Handles car setups with deep mechanical knowledge.',
    profile_image_url: null,
    helmet_image_url: '/members/minsoo_helmet.png',
    is_published: true,
    sort_order: 4,
  },
  {
    id: 'm-05',
    slug: 'taeyun-lee',
    racing_number: '05',
    name: 'Taeyun Lee',
    field: 'Onroad',
    role: 'leader',
    favorite_car: 'POR 935',
    favorite_track: 'Nürburgring',
    birth_year: 2009,
    wheel_base: 'MOZA R5',
    pedal: 'MOZA CRP2',
    instagram: 't.xyn.09',
    bio_ko: null,
    bio_en: 'Looking for a lovely lady to date, slide into DMs.',
    profile_image_url: null,
    helmet_image_url: '/members/taeyun_helmet.png',
    is_published: true,
    sort_order: 5,
  },
];

export const cars: Car[] = [
  { id: 'c-01', name: 'McLaren 720S GT3', manufacturer: 'McLaren', car_class: 'GT3', description_ko: null, description_en: null, image_url: null, is_published: true },
  { id: 'c-02', name: 'BMW M4 GT3', manufacturer: 'BMW', car_class: 'GT3', description_ko: null, description_en: null, image_url: null, is_published: true },
  { id: 'c-03', name: 'SF-24', manufacturer: 'Dallara', car_class: 'Formula', description_ko: null, description_en: null, image_url: null, is_published: true },
  { id: 'c-04', name: 'Toyota GR86', manufacturer: 'Toyota', car_class: 'Sports Car', description_ko: null, description_en: null, image_url: null, is_published: true },
  { id: 'c-05', name: 'Porsche 935', manufacturer: 'Porsche', car_class: 'GT2', description_ko: null, description_en: null, image_url: null, is_published: true },
];

const byId = (id: string) => members.find((m) => m.id === id)!;

export const races: Race[] = [
  {
    id: 'r-03',
    slug: 'nurburgring-endurance-6h-2026',
    title_ko: 'Nürburgring Endurance 6H',
    title_en: 'Nürburgring Endurance 6H',
    status: 'upcoming',
    starts_at: '2026-07-05T21:00:00+09:00',
    platform: 'iRacing',
    series: 'Nürburgring Endurance Championship',
    circuit_name: 'Nürburgring',
    circuit_info_ko: null,
    circuit_info_en: null,
    track_map_url: null,
    race_length: '6H',
    car_class: 'GT3',
    thumbnail_url: null,
    youtube_url: null,
    description_ko: 'Taeyun Lee 선수가 용병 Donggeon Kim과 함께 Nürburgring Endurance 6H Race에 출전합니다.',
    description_en: 'Taeyun Lee will race in the Nürburgring Endurance 6H with guest driver Donggeon Kim.',
    review_ko: null,
    review_en: null,
    is_published: true,
    result: null,
    members: [byId('m-05')],
    cars: [],
  },
  {
    id: 'r-02',
    slug: 'sebring-3h-2026',
    title_ko: 'Sebring 3H Race',
    title_en: 'Sebring 3H Race',
    status: 'completed',
    starts_at: '2026-03-27T21:00:00+09:00',
    platform: 'iRacing',
    series: null,
    circuit_name: 'Sebring International Raceway',
    circuit_info_ko: null,
    circuit_info_en: null,
    track_map_url: null,
    race_length: '3H',
    car_class: 'GT3',
    thumbnail_url: null,
    youtube_url: null,
    description_ko: null,
    description_en: null,
    review_ko: 'Minsoo Seo와 Taeyun Lee가 호흡을 맞춰 처음으로 레이스 10위권으로 완주하였습니다.',
    review_en: 'Minsoo Seo and Taeyun Lee teamed up to finish in the top 10 for the first time.',
    is_published: true,
    result: {
      race_id: 'r-02',
      overall_pos: 10,
      class_pos: null,
      qualifying_pos: 8,
      fastest_lap: null,
      incidents: null,
      finish_status: 'Finished',
      notes_ko: null,
      notes_en: null,
    },
    members: [byId('m-04'), byId('m-05')],
    cars: [],
  },
  {
    id: 'r-01',
    slug: 'nurburgring-endurance-cup-4h-2026',
    title_ko: 'Nürburgring Endurance Cup 4H',
    title_en: 'Nürburgring Endurance Cup 4H',
    status: 'completed',
    starts_at: '2026-03-22T21:00:00+09:00',
    platform: 'iRacing',
    series: 'Nürburgring Endurance Cup',
    circuit_name: 'Nürburgring',
    circuit_info_ko: null,
    circuit_info_en: null,
    track_map_url: null,
    race_length: '4H',
    car_class: 'GT3',
    thumbnail_url: null,
    youtube_url: null,
    description_ko: null,
    description_en: null,
    review_ko: 'Nürburgring Endurance Cup 4H 레이스에서 최종 26등으로 안전하게 완주하였습니다.',
    review_en: 'Safely finished P26 overall in the Nürburgring Endurance Cup 4H race.',
    is_published: true,
    result: {
      race_id: 'r-01',
      overall_pos: 26,
      class_pos: null,
      qualifying_pos: 11,
      fastest_lap: null,
      incidents: null,
      finish_status: 'Finished',
      notes_ko: null,
      notes_en: null,
    },
    members: [byId('m-01'), byId('m-04'), byId('m-05')],
    cars: [],
  },
];

export const news: NewsPost[] = [
  {
    id: 'n-03',
    slug: 'nurburgring-6h-entry',
    title_ko: 'Nürburgring Endurance 6H Race 출전',
    title_en: 'Entering Nürburgring Endurance 6H',
    category: 'race',
    summary_ko: '7월 5일에 Taeyun Lee 선수가 용병 Donggeon Kim과 함께 출전합니다.',
    summary_en: 'Taeyun Lee will race with Donggeon Kim on July 5th.',
    body_ko: '7월 5일에 Taeyun Lee 선수가 용병 Donggeon Kim과 함께 Nürburgring Endurance 6H Race에 출전합니다.',
    body_en: 'Taeyun Lee will race in the Nürburgring 6H with Donggeon Kim on July 5th.',
    cover_image_url: null,
    author: 'TRL Racing',
    published_at: '2026-07-02T12:00:00+09:00',
    related_race_id: 'r-03',
    is_published: true,
  },
  {
    id: 'n-02',
    slug: 'sebring-3h-top10',
    title_ko: 'Sebring 3H Race 첫 10위권',
    title_en: 'Top 10 finish at Sebring 3H',
    category: 'result',
    summary_ko: 'Minsoo Seo와 Taeyun Lee가 처음으로 레이스 10위권으로 완주했습니다.',
    summary_en: 'First-ever top 10 finish for Minsoo Seo and Taeyun Lee.',
    body_ko: 'Minsoo Seo와 Taeyun Lee가 호흡을 맞춰 처음으로 레이스 10위권으로 완주하였습니다.',
    body_en: 'Minsoo Seo and Taeyun Lee teamed up to finish in the top 10 for the first time.',
    cover_image_url: null,
    author: 'TRL Racing',
    published_at: '2026-03-27T23:00:00+09:00',
    related_race_id: 'r-02',
    is_published: true,
  },
  {
    id: 'n-01',
    slug: 'nurburgring-4h-p26',
    title_ko: 'Nürburgring Endurance Cup 4H 레이스 P26 완주',
    title_en: 'P26 finish at Nürburgring 4H',
    category: 'result',
    summary_ko: 'Nürburgring Endurance Cup 4H 레이스에서 최종 26등으로 완주했습니다.',
    summary_en: 'Safely finished P26 overall at the Nürburgring 4H.',
    body_ko: 'Nürburgring Endurance Cup 4H 레이스에서 최종 26등으로 안전하게 완주하였습니다.',
    body_en: 'Safely finished P26 overall in the Nürburgring Endurance Cup 4H race.',
    cover_image_url: null,
    author: 'TRL Racing',
    published_at: '2026-03-22T23:00:00+09:00',
    related_race_id: 'r-01',
    is_published: true,
  },
];

export const gallery: GalleryImage[] = members.map((m, i) => ({
  id: `g-0${i + 1}`,
  image_url: m.helmet_image_url!,
  caption_ko: `${m.name} 헬멧`,
  caption_en: `${m.name} Helmet`,
  shot_at: null,
  related_race_id: null,
  is_published: true,
  sort_order: i + 1,
}));

export const settings: SiteSettings = {
  hero_video_url: '',
  recruiting: true,
  discord_url: '',
  instagram_url: 'https://www.instagram.com/torqueline_racing/',
  youtube_url: 'https://www.youtube.com/@torqueline_racing',
  contact_url: '',
};
